🐛(editor) fix TypeError in document editor
I get

> TypeError: Cannot use 'in' operator to search for 'de' in undefined

when building MIT-only since `localesBNAI` is undefined then.

Signed-off-by: Maximilian Bosch <maximilian@mbosch.me>